#!/bin/sh
#
set -euf -o pipefail

bot_api="https://api.telegram.org/bot"
for f in /etc/telegraph.cfg $HOME/.telegraph.cfg
do
  [ -f "$f" ] && . "$f"
done
unset f

urlencode() {
  # urlencode <string>
  old_lc_collate=${LC_COLLATE:-}
  LC_COLLATE=C
  
  local length="${#1}"
  local i=1
  while [ $i -le $length ] ; do
    local c=$(expr substr "$1" $i 1)
    case $c in
      [a-zA-Z0-9.~_-]) printf "$c" ;;
      *) printf '%%%02X' "'$c" ;;
    esac
    i=$(expr $i + 1)
  done
  
  LC_COLLATE=$old_lc_collate
}

send_notification() {
  wget -O- "${bot_api}${bot_key}/sendMessage?chat_id=${chat_id}&text=$(urlencode "$*")"
}

send_notification "$@"
